04_program/Qualify/Qualify/Models/Claim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Qualify.Models
{
    public class Claim
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public string Title { get; set; }
        public string? Description { get; set; }
        public string? Dirpath { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateStart { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DateEnd { get; set; }

        public Client Client { get; set; }
        public ICollection<ClaimHistory> ClaimHistories { get; set; }
        public ICollection<ClaimExpence> ClaimExpences { get; set; }
    }
}

04_program/Qualify/Qualify/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.FileProviders.Physical;
using Qualify.Models;
using Qualify.Repository;

namespace Qualify.Controllers
{
    public class ClaimController : Controller
    {
        private readonly ClaimRepository _claimRepository = null;
        private readonly ClientRepository _clientRepository = null;
        private readonly ClaimHistoryRepository _historytRepository = null;
        private readonly EmployeeRepository _employeeRepository = null;

        public ClaimController(ClaimRepository claimRepository, ClientRepository clientRepository, ClaimHistoryRepository claimHistoryRepository, EmployeeRepository employeeRepository)
        {
            _claimRepository = claimRepository;
            _clientRepository = clientRepository;
            _historytRepository = claimHistoryRepository;
            _employeeRepository = employeeRepository;
        }
        public async Task<ViewResult> Index()
        {
            ViewBag.ClientsList = await _clientRepository.GetClients();
            var data = await _claimRepository.GetAllClaims();
            return View(data);
        }

        
        public async Task<ViewResult> ViewClaim(int id) 
        {
            var data = await _claimRepository.GetClaimById(id);
            ViewBag.ClaimId = id;
            var currentClient = await _clientRepository.GetClientNameByClaimId(id);
            ViewBag.ClientName = currentClient.Name;
            ViewBag.CurrentHistory = await _historytRepository.GetHistoriesByClaimId(id);
            ViewBag.EmployeeList = await _employeeRepository.GetEmployees();

            return View(data);
        }

        public async Task<ViewResult> AddClaim(bool isSuccess = false, int claimId = 0)
        {
            var model = new Claim() 
            { 

            };

            ViewBag.Clients = new SelectList(await _clientRepository.GetClients(), "ID", "Name");

            ViewBag.Success = isSuccess;
            ViewBag.ClaimId = claimId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddClaim(Claim claim)
        {
            int id = await _claimRepository.AddClaim(claim);
            if (id > 0)
            {
                return RedirectToAction(nameof(AddClaim), new {isSuccess = true, claimId = id});
            }

            ViewBag.Clients = new SelectList(await _clientRepository.GetClients(), "ID", "Name");

            return View();
        }
    }
}

04_program/Qualify/Qualify/Controllers/ClaimHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Qualify.Models;
using Qualify.Repository;

namespace Qualify.Controllers
{
    public class ClaimHistoryController : Controller
    {
        
        private readonly EmployeeRepository _employeeRepository = null;
        private readonly ClaimHistoryRepository _historyRepository = null;
        public ClaimHistoryController(ClaimHistoryRepository claimHistoryRepository, EmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
            _historyRepository = claimHistoryRepository;
        }

        public async Task<ViewResult> AddHistory(bool isSuccess = false, int claimId = 0)
        {
            var model = new ClaimHistory()
            {

            };
            ViewBag.Employees = new SelectList(await _employeeRepository.GetEmployees(), "ID", "Name");
            ViewBag.Success = isSuccess;
            ViewBag.ClaimId = claimId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddHistory(ClaimHistory claimHistory, int claimId)
        {
            
            int id = await _historyRepository.AddHistory(claimHistory, claimId);
            if (id > 0)
            {
                return RedirectToAction("ViewClaim", "Claim", new { id = claimId});
            }

            ViewBag.Employees = new SelectList(await _employeeRepository.GetEmployees(), "ID", "Name");

            return View();
        }
    }
}

04_program/Qualify/Qualify/Views/Claim/AddClaim.cshtml
@using Qualify.Models
@model Claim
@{
    ViewData["Title"] = "Создать рекламацию...";

}
@if (ViewBag.Success == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Всё в порядке.</strong> Вы успешно добавили рекламацию.<br />
        Нажмите <a asp-controller="Claim" asp-action="ViewClaim" asp-route-id="@ViewBag.ClaimId">здесь</a>, чтобы просмотреть введенную информацию.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<form method="post" asp-action="AddClaim">

    <label asp-for="ClientID" class="form-label">Клиент</label>
    <select asp-for="ClientID" class="form-control" asp-items="ViewBag.Clients">
        <option value="">---Выберите имя клиента---</option>
    </select>

    <label asp-for="Title" class="form-label">Заголовок</label>
    <input asp-for="Title" class="form-control" />

    <label asp-for="Description" class="form-label">Описание</label>
    <textarea asp-for="Description" class="form-control"></textarea>

    <label asp-for="DateStart" class="form-label">Дата регистрации</label>
    <input type="date" asp-for="DateStart" class="form-control" />

    <input type="submit" value="Подать рекламацию" class="form-button button btn-success" />


</form>

04_program/Qualify/Qualify/Views/Claim/Index.cshtml
@using Qualify.Models
@model IEnumerable<Claim>
@{
    ViewData["Title"] = "Список рекламаций";
}

<nav id="breadcrumbs">
    <div class="metabox">
        <a class="metabox-main" asp-controller="Home" asp-action="Index"><i class="fa fa-home" aria-hidden="true"></i> Главная</a>
        <a class="metabox-main" asp-controller="Claim" asp-action="Index">Claims</a>
    </div>
</nav>

<div class="actionbar">
    <div class="actionbox"><a class="button btn-primary" asp-controller="claim" asp-action="addclaim">Добавить</a></div>
    <div class="actionbox">
        <form>
            <input class="inline fromleft" type="search" placeholder="Поиск...">
            <input class="fromright" type="submit" value="Найти">
        </form>
    </div>
</div>

<div class="contentfield">

    <div class="table">
        <div class="row-headings">
            <div class="cell id"><span>#</span></div>
            <div class="cell client"><span>Клиент</span></div>
            <div class="cell title"><span>Заголовок</span></div>
            <div class="cell desc"><span>Описание</span></div>
            <div class="cell start"><span>Начало</span></div>
            <div class="cell finish"><span>Окончание</span></div>
        </div>
        <div class="table-content">
            @foreach (var claim in Model)
            {
                string currentClientName = "Undefined Client";
                string dateFrom = claim.DateStart.ToString("yyyy-MM-dd");
                string dateTill = "_";
                foreach (var client in ViewBag.ClientsList)
                {
                    if (client.ID == claim.ClientID)
                    {
                        currentClientName = client.Name;
                    }
                }

                if (claim.DateEnd.HasValue)
                {
                    dateTill = claim.DateEnd.ToString();
                } else
                {
                    dateTill = "---";
                }

                <a class="row" asp-controller="Claim" asp-action="ViewClaim" asp-route-id="@claim.ID">
                    <div class="cell id"><span>@claim.ID</span></div>
                    <div class="cell client"><span>@currentClientName</span></div>
                    <div class="cell title"><p>@claim.Title</p></div>
                    <div class="cell desc"><p>@claim.Description</p></div>
                    <div class="cell start"><span>@dateFrom</span></div>
                    <div class="cell finish"><span>@dateTill</span></div>
                </a>
            }
        </div>
    </div>

</div>

04_program/Qualify/Qualify/Views/Claim/ViewClaim.cshtml
@using Qualify.Models
@model Claim
@{
    ViewData["Title"] = "Рекламация №" + ViewBag.ClaimId;
}

<nav id="breadcrumbs">
    <div class="metabox">
        <a class="metabox-main" asp-controller="Home" asp-action="Index"><i class="fa fa-home" aria-hidden="true"></i> Главная</a>
        <a class="metabox-main" asp-controller="Claim" asp-action="Index">Рекламации</a>
        <a class="metabox-main" asp-controller="Claim" asp-action="ViewClaim" asp-route-id="@ViewBag.ClaimId">@ViewBag.ClaimId</a>
    </div>
</nav>

<div class="contentfield">
    <div class="claim-entity">
        <div class="claim-body">
            <h2 class="claim-heading">@Model.Title</h2>
            <hr class="divider">
            <div class="claim-objective">
                <div class="claim-img">
                    @{
                        //string docpath = "docs/claims/" + Model.ID + "/" + Model.Dirpath;
                        string imgpath = "../../img/claims/" + Model.ID + "/" + Model.Dirpath;
                     }
                    <img class="claimimg" src="@imgpath">
                </div>
                <div class="claim-details">
                    <div class="details"><span class="claim-client">@ViewBag.ClientName</span></div>
                    <div class="details"><span class="claim-datestart">@Model.DateStart.ToString("yyyy-MM-dd")</span></div>
                    @if (Model.DateEnd != null)
                    {
                        <div class="details"><span class="claim-datefinish">@Model.DateEnd</span></div>
                    }
                    else
                    {
                        <div class="details"><span class="claim-datefinish">Ещё не закрыта</span></div>
                    }
                    
                    <div class="details"><span class="claim-totalexpences">3 256,35 €</span></div>
                </div>
            </div>
            <div class="claim-description">
                <p>Прицеп в ненадлежащем состоянии. При попытке ввода в эксплуатацию обнаружены неисправности, описанные в приложенном отчёте.</p>
            </div>
        </div>
        <div class="claim-actions">
            <h4>Действия по рекламации</h4>
            <hr class="divider">

            <div class="table">

                <div class="row-headings">
                    <div class="cell id"><span>#</span></div>
                    <div class="cell caction-desc"><span>Описание</span></div>
                    <div class="cell caction-responsible"><span>Ответственный</span></div>
                    <div class="cell caction-startdate"><span>Начало</span></div>
                    <div class="cell caction-finishdate"><span>Окончание</span></div>
                    <div class="cell caction-status"><span>Статус</span></div>
                </div>

                @{
                    if (ViewBag.CurrentHistory?.Count > 0 )
                    {
                        foreach (var claimAction in ViewBag.CurrentHistory)
                        {
                            string currentResponsibleName = "Undefined responsible";
                            string endDate = "0000-00-00";
                            foreach (var human in ViewBag.EmployeeList)
                            {
                                if(human.ID == claimAction.EmployeeID)
                                {
                                    currentResponsibleName = human.Name;
                                }

                            }

                            if (claimAction.DateEnd != null)
                            {
                                endDate = claimAction.DateEnd.ToString("yyyy-MM-dd");
                            }
                            else
                            {
                                endDate = "---";
                            }

                            <a class="row" href="#">
                                <div class="cell id"><span>@claimAction.ID</span></div>
                                <div class="cell caction-desc"><p>@claimAction.Description</p></div>
                                <div class="cell caction-responsible"><span>@currentResponsibleName</span></div>
                                <div class="cell caction-startdate"><span>@claimAction.DateStart.ToString("yyyy-MM-dd")</span></div>
                                <div class="cell caction-finishdate"><span>@endDate</span></div>
                                <div class="cell caction-status"><span>@claimAction.Performed</span></div>
                            </a>
                        }
                    }
                    else
                    {
                        <a class="row" href="#">
                            <div class="cell id"><span>---</span></div>
                            <div class="cell caction-desc"><p>---</p></div>
                            <div class="cell caction-responsible"><span>---</span></div>
                            <div class="cell caction-startdate"><span>---</span></div>
                            <div class="cell caction-finishdate"><span>---</span></div>
                            <div class="cell caction-status"><span>---</span></div>
                        </a>
                    }

                }
            </div>

            <div class="actionbar">
                <div class="actionbox"><a class="button btn-primary" asp-controller="ClaimHistory" asp-action="AddHistory" asp-route-ClaimID="@ViewBag.ClaimId">Добавить</a></div>
            </div>

        </div>

        <div class="claim-expences">
            <h4>Расходы по рекламации</h4>
            <hr class="divider">
            <div class="table">
                <div class="row-headings">
                    <div class="cell id"><span>#</span></div>
                    <div class="cell cexp-type"><span>Тип</span></div>
                    <div class="cell cexp-desc"><span>Описание</span></div>
                    <div class="cell cexp-sum"><span>Сумма</span></div>
                    <div class="cell cexp-date"><span>Дата расхода</span></div>
                    <div class="cell cexp-owner"><span>Плательщик</span></div>
                </div>
                <a class="row" href="#">
                    <div class="cell id"><span>1</span></div>
                    <div class="cell cexp-type"><span>Затраты клиента</span></div>
                    <div class="cell cexp-desc">
                        <p>Клиент вынужден был сам перекрашивать кузов прицепа</p>
                    </div>
                    <div class="cell cexp-sum"><span>3 256,35 €</span></div>
                    <div class="cell cexp-date"><span>2020-02-03</span></div>
                    <div class="cell cexp-owner"><span>Покрасочный цех</span></div>
                </a>
            </div>
            <div class="actionbar">
                <div class="actionbox"><a class="button btn-primary" href="#">Добавить</a></div>
            </div>
        </div>

        <div class="claim-documents">
            <h4>Связанные документы</h4>
            <hr class="divider">
            <div class="table">
                <div class="row-headings">
                    <div class="cell id"><span>#</span></div>
                    <div class="cell cdocs-name"><span>Название</span></div>
                    <div class="cell cdocs-type"><span>Тип</span></div>
                    <div class="cell cdocs-desc"><span>Описание</span></div>
                    <div class="cell cdocs-date"><span>Дата добав.</span></div>
                    <div class="cell cdocs-status"><span>Статус</span></div>
                </div>
                <a class="row" href="#">
                    <div class="cell id"><span>1</span></div>
                    <div class="cell cdocs-name"><span>F0-2020-06-05/001</span></div>
                    <div class="cell cdocs-type"><span>Invoice</span></div>
                    <div class="cell cdocs-desc"><p>Логистика</p></div>
                    <div class="cell cdocs-date"><span>2020-02-03</span></div>
                    <div class="cell cdocs-status"><span>Активный</span></div>
                </a>
            </div>
            <div class="actionbar">
                <div class="actionbox"><a class="button btn-primary" href="#">Добавить</a></div>
            </div>
        </div>
    </div>
</div>