04_program/Qualify/Qualify/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.FileProviders.Physical;
using Qualify.Models;
using Qualify.Repository;

namespace Qualify.Controllers
{
    public class ClaimController : Controller
    {
        private readonly ClaimRepository _claimRepository = null;
        private readonly ClientRepository _clientRepository = null;
        private readonly ClaimHistoryRepository _historytRepository = null;
        private readonly EmployeeRepository _employeeRepository = null;

        public ClaimController(ClaimRepository claimRepository, ClientRepository clientRepository, ClaimHistoryRepository claimHistoryRepository, EmployeeRepository employeeRepository)
        {
            _claimRepository = claimRepository;
            _clientRepository = clientRepository;
            _historytRepository = claimHistoryRepository;
            _employeeRepository = employeeRepository;
        }
        public async Task<ViewResult> Index()
        {
            ViewBag.ClientsList = await _clientRepository.GetClients();
            var data = await _claimRepository.GetAllClaims();
            return View(data);
        }

        
        public async Task<ViewResult> ViewClaim(int id) 
        {
            var data = await _claimRepository.GetClaimById(id);
            ViewBag.ClaimId = id;
            var currentClient = await _clientRepository.GetClientNameByClaimId(id);
            ViewBag.ClientName = currentClient.Name;
            ViewBag.CurrentHistory = await _historytRepository.GetHistoriesByClaimId(id);
            ViewBag.EmployeeList = await _employeeRepository.GetEmployees();

            return View(data);
        }

        public async Task<ViewResult> AddClaim(bool isSuccess = false, int claimId = 0)
        {
            var model = new Claim() 
            { 

            };

            ViewBag.Clients = new SelectList(await _clientRepository.GetClients(), "ID", "Name");

            ViewBag.Success = isSuccess;
            ViewBag.ClaimId = claimId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddClaim(Claim claim)
        {
            int id = await _claimRepository.AddClaim(claim);
            if (id > 0)
            {
                return RedirectToAction(nameof(AddClaim), new {isSuccess = true, claimId = id});
            }

            ViewBag.Clients = new SelectList(await _clientRepository.GetClients(), "ID", "Name");

            return View();
        }
    }
}

04_program/Qualify/Qualify/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Qualify.Models;
using Qualify.Repository;

namespace Qualify.Controllers
{
    public class HomeController : Controller
    {
        private readonly ClaimRepository _claimRepository = null;
        private readonly ClientRepository _clientRepository = null;
        private readonly ClaimHistoryRepository _historytRepository = null;
        private readonly EmployeeRepository _employeeRepository = null;

        public HomeController(ClaimRepository claimRepository, ClientRepository clientRepository, ClaimHistoryRepository claimHistoryRepository, EmployeeRepository employeeRepository)
        {
            _claimRepository = claimRepository;
            _clientRepository = clientRepository;
            _historytRepository = claimHistoryRepository;
            _employeeRepository = employeeRepository;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.ClientsList = await _clientRepository.GetClients();
            var data = await _claimRepository.GetAllClaims();
            var openClaims = new List<Claim>();
            foreach(var claim in data)
            {
                if (claim.DateEnd == null)
                {
                    openClaims.Add(new Claim() 
                    { 
                        ID = claim.ID,
                        ClientID = claim.ClientID,
                        Title = claim.Title,
                        Description = claim.Description,
                        Dirpath = claim.Dirpath,
                        DateStart = claim.DateStart
                    });
                }
            }
            return View(openClaims); 
        }
    }
}

04_program/Qualify/Qualify/Views/Home/Index.cshtml
@using Qualify.Models
@model IEnumerable<Claim>
@{
    ViewData["Title"] = "Qualify";
}

    <div class="contentfield">
        <div class="claim-entity">
            <h4>Открытые рекламации:</h4>
            <hr class="divider">
            <div class="table">
                <div class="row-headings">
                    <div class="cell id"><span>#</span></div>
                    <div class="cell client"><span>Клиент</span></div>
                    <div class="cell title"><span>Заголовок</span></div>
                    <div class="cell desc"><span>Описание</span></div>
                    <div class="cell start"><span>Зарегистрирована</span></div>
                </div>
                
                @foreach (var claim in Model)
                {
                    string currentClientName = "Undefined Client";
                    foreach (var client in ViewBag.ClientsList)
                    {
                        if (client.ID == claim.ClientID)
                        {
                            currentClientName = client.Name;
                        }
                    }
                    
                    <a class="row" asp-controller="Claim" asp-action="ViewClaim" asp-route-id="@claim.ID">
                        <div class="cell id"><span>@claim.ID</span></div>
                        <div class="cell client"><span>@currentClientName</span></div>
                        <div class="cell title"><p>@claim.Title</p></div>
                        <div class="cell desc"><p>@claim.Description</p></div>
                        <div class="cell start"><span>@claim.DateStart.ToString("yyyy-MM-dd")</span></div>
                    </a>
                }
                
            </div>
        </div>
    </div>